version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL
      - DB_USER
      - DB_PASSWORD
    depends_on:
      - db
      - flyway

  db:
    image: postgres:15.7
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10.15.0
    command: -url=${DB_URL} -user=${DB_USER} -password=${DB_PASSWORD} -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./src/main/resources/sql:/flyway/sql
    depends_on:
      - db

volumes:
  pgdata:
